# Generated by Django 4.2.2 on 2023-07-19 02:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


def generate_unique_tokens(apps, schema_editor) -> None:
    """Generate unique tokens for existing contracts."""
    contracts = apps.get_model("members", "Contract").objects.all()
    for contract in contracts:
        contract.token = uuid.uuid4()
        contract.save()


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0008_alter_usercampaign_role'),
        ('members', '0003_contract_campaign_contract_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token', null=True),
        ),
        migrations.RunPython(
            generate_unique_tokens,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='contract',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token', null=False),
        ),
    ]
