# Generated by Django 4.2.2 on 2023-07-27 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0004_contract_campaign_contract_name_contract_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='members.contract', verbose_name='Contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(default=1, editable=False, max_length=50, verbose_name='Invoice number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(null=True, verbose_name='Sent at'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=1, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='representative',
            field=models.CharField(default=1, max_length=255, verbose_name='Representative'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='member',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
