# Generated by Django 4.2.2 on 2023-08-17 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_productcategory_background_color_and_more'),
        ('members', '0005_remove_contract_invoice_invoice_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to='campaigns.usercampaign', verbose_name='Created By'),
            preserve_default=False,
        ),
    ]
