# Generated by Django 4.2.2 on 2023-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_contract_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Private Note'),
        ),
    ]
