# Generated by Django 4.2.5 on 2023-10-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_contractsharedcreditinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signature',
            field=models.TextField(blank=True, default='', verbose_name='Signature'),
        ),
    ]
