# Generated by Django 4.2.5 on 2023-11-15 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_contract_is_approved_contract_approved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
    ]
