# Generated by Django 4.2.7 on 2023-11-30 02:27

from django.db import migrations, models


def update_contract_renew_flag(apps, schema_editor):
    """Update contracts' renew flag."""
    Contract = apps.get_model("members.Contract")
    Contract.objects.filter(
        campaign__is_renewed=True,
        campaign__status__in=("renewal", "live"),
    ).update(is_renewed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_contractcreditinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_renewed',
            field=models.BooleanField(default=False, verbose_name='Is Renewed'),
        ),
        migrations.RunPython(
            update_contract_renew_flag,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
