# Generated by Django 4.2.7 on 2023-12-08 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0015_alter_storedmember_options_alter_chamber_subdomain'),
        ('members', '0017_contract_is_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stored_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chambers.storedmember', verbose_name='Stored member'),
        ),
    ]
