# Generated by Django 4.2.7 on 2023-12-08 08:19
import decimal

from django.db import migrations, models
import itertools
import operator


def recalculate_portion_precision(apps, schema_editor):
    """Fix portion field's precision."""
    ContractCreditInfo = apps.get_model("members.ContractCreditInfo")
    contract_credits_info = ContractCreditInfo.objects.all().order_by(
        "contract_id",
    )
    updated_contract_credits = []
    for contract_id, contract_credits_group in itertools.groupby(
        contract_credits_info,
        key=operator.attrgetter("contract_id"),
    ):
        contract_credits = list(contract_credits_group)
        credits_count = len(contract_credits)
        for contract_credit in contract_credits:
            contract_credit.portion = decimal.Decimal(1 / credits_count)
        updated_contract_credits.extend(contract_credits)
    ContractCreditInfo.objects.bulk_update(
        updated_contract_credits,
        fields=["portion"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_member_stored_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcreditinfo',
            name='portion',
            field=models.DecimalField(decimal_places=14, max_digits=15, verbose_name='Portion'),
        ),
        migrations.RunPython(
            recalculate_portion_precision,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
