# Generated by Django 4.2.9 on 2024-01-23 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0041_campaign_external_id_campaign_external_position_and_more'),
        ('members', '0019_alter_contractcreditinfo_portion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcreditinfo',
            name='user_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts_credit_info', to='campaigns.usercampaign', verbose_name='User campaign'),
        ),
    ]
