# Generated by Django 4.2.9 on 2024-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_contractcreditinfo_user_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID in old DB'),
        ),
    ]
