# Generated by Django 4.2.10 on 2024-03-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_alter_member_mobile_phone_alter_member_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signer_ip_address',
            field=models.CharField(blank=True, max_length=45, verbose_name="Signer's IP address"),
        ),
    ]
