# Generated by Django 4.2.10 on 2024-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0024_alter_member_mobile_phone_alter_member_work_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="zipcode",
            field=models.CharField(max_length=10, verbose_name="Zip code"),
        ),
    ]
