# Generated by Django 4.2.10 on 2024-04-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0025_alter_member_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="name",
            field=models.CharField(editable=False, max_length=300, verbose_name="Name"),
        ),
    ]
