# Generated by Django 4.2.2 on 2023-07-10 09:42

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('campaigns', '0003_campaign_deleted_at_campaign_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('threshold', models.IntegerField(default=0, verbose_name='Threshold')),
                ('value', models.IntegerField(default=0, verbose_name='Value')),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('gift_card', 'Gift Card')], max_length=20, verbose_name='Type')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to='campaigns.campaign', verbose_name='Campaign ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncentiveQualifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(choices=[('sells', 'Sells'), ('amount', 'Amount'), ('clients', 'Clients')], max_length=20, verbose_name='Name')),
                ('amount', models.IntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (100, '100')], verbose_name='Amount')),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='incentives.incentive', verbose_name='Incentive ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
