# Generated by Django 4.2.5 on 2023-09-26 11:13

from django.db import migrations, models


def populate_incentive_order_data(apps, schema_editor) -> None:
    """Populate incentive data with order field for each campaign."""
    Incentive = apps.get_model("incentives", "Incentive")
    Campaign = apps.get_model("campaigns", "Campaign")
    incenties = Incentive.objects.select_related("campaign")
    updated_incentives = {
        incentive: idx
        for campaign in Campaign.objects.all()
        for idx, incentive in enumerate(incenties.filter(campaign=campaign))
    }
    for incentive, idx in updated_incentives.items():
        incentive.order = idx
    Incentive.objects.bulk_update(updated_incentives.keys(), fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0002_alter_incentive_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incentive',
            options={'ordering': ('order',), 'verbose_name': 'Incentive', 'verbose_name_plural': 'Incentives'},
        ),
        migrations.AddField(
            model_name='incentive',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_incentive_order_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
