# Generated by Django 4.2.5 on 2023-11-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0003_alter_incentive_options_incentive_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentive',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='type',
            field=models.CharField(choices=[('cash', 'Cash'), ('trip', 'Trip'), ('trade', 'Trade'), ('other', 'Other')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='incentive',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
