# Generated by Django 4.2.9 on 2024-01-22 07:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0041_campaign_external_id_campaign_external_position_and_more'),
        ('incentives', '0004_alter_incentive_threshold_alter_incentive_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('incentive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='incentives.incentive', verbose_name='Incentive')),
                ('user_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='campaigns.usercampaign', verbose_name='User Campaign')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
            },
        ),
    ]
