# Generated by Django 4.2.9 on 2024-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incentives', '0005_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentive',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID in old DB'),
        ),
        migrations.AddField(
            model_name='reward',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID in old DB'),
        ),
    ]
