# Generated by Django 4.2.2 on 2023-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chambers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
    ]
