# Generated by Django 4.2.2 on 2023-06-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chambers', '0002_chamber_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='chamberbranding',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chamberbranding',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
