# Generated by Django 4.2.2 on 2023-06-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chambers', '0003_chamber_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamber',
            name='trc_coord_name',
        ),
        migrations.AddField(
            model_name='chamber',
            name='trc_coord_first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='TRC Coord First name'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='trc_coord_last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='TRC Coord Last name'),
        ),
    ]
