# Generated by Django 4.2.2 on 2023-07-05 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('chambers', '0004_remove_chamber_trc_coord_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamberbranding',
            name='chamber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='chambers.chamber', verbose_name='Chamber'),
        ),
        migrations.AlterField(
            model_name='chamberbranding',
            name='chamber_logo',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='', verbose_name='Chamber Logo'),
        ),
        migrations.AlterField(
            model_name='chamberbranding',
            name='landing_bg',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='', verbose_name='Landing background image'),
        ),
        migrations.AlterField(
            model_name='chamberbranding',
            name='trc_logo',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='', verbose_name='Chamber Logo'),
        ),
    ]
