# Generated by Django 4.2.2 on 2023-07-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chambers', '0005_alter_chamberbranding_chamber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='mail_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mail Address'),
        ),
    ]
