# Generated by Django 4.2.2 on 2023-07-17 07:18
from django.contrib.postgres.operations import CreateCollation
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chambers', '0006_alter_chamber_mail_address'),
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        ),
        migrations.AlterField(
            model_name='chamber',
            name='nickname',
            field=models.CharField(db_collation='case_insensitive', max_length=255, unique=True, verbose_name='Nick Name'),
        ),
    ]
