# Generated by Django 4.2.2 on 2023-08-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0010_storedmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedmember',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Address'),
        ),
    ]
