# Generated by Django 4.2.2 on 2023-08-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0011_storedmember_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='storedmember',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='storedmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='storedmember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='storedmember',
            name='phone',
        ),
        migrations.AddField(
            model_name='storedmember',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company City'),
        ),
        migrations.AddField(
            model_name='storedmember',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='storedmember',
            name='contact_first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact First Name'),
        ),
        migrations.AddField(
            model_name='storedmember',
            name='contact_last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Last Name'),
        ),
        migrations.AddField(
            model_name='storedmember',
            name='contact_mobile_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Work Phone'),
        ),
        migrations.AddField(
            model_name='storedmember',
            name='contact_work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contact Work Phone'),
        ),
        migrations.AddField(
            model_name='storedmember',
            name='name',
            field=models.CharField(default='Default Company', max_length=255, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storedmember',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company State'),
        ),
        migrations.AddField(
            model_name='storedmember',
            name='zip',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Zip'),
        ),
        migrations.AlterField(
            model_name='storedmember',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Address'),
        ),
    ]
