# Generated by Django 4.2.2 on 2023-08-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0012_remove_storedmember_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedmember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='storedmember',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='Company State'),
        ),
        migrations.AlterField(
            model_name='storedmember',
            name='zip',
            field=models.CharField(blank=True, max_length=15, verbose_name='Company Zip'),
        ),
    ]
