# Generated by Django 4.2.2 on 2023-09-13 03:15

from django.db import migrations, models


def populate_first_and_last_names_and_create_ceo_admin(apps, schema_editor):
    """Populate new first_name, last_name fields and create ceo admins."""
    Chamber = apps.get_model("chambers.Chamber")
    User = apps.get_model("users.User")
    chambers = Chamber.objects.all()
    new_ceo_admins = []
    for chamber in chambers:
        ceo_email = chamber.ceo_email
        if not ceo_email:
            continue
        ceo_name: str = chamber.ceo_name or "Default Name"
        if " " in ceo_name:
            first_name, last_name = ceo_name.split(" ", maxsplit=1)
        else:
            first_name, last_name = ceo_name, ""
        chamber.ceo_first_name = first_name
        chamber.ceo_last_name = last_name
        idx = ceo_email.index("@")
        ceo_email = ceo_email[:idx] + str(chamber.id) + ceo_email[idx:]
        chamber.ceo_email = ceo_email
        ceo_admin = User(
            first_name=first_name,
            last_name=last_name,
            email=ceo_email,
            mobile_phone=chamber.ceo_phone,
            role="chamber_admin",
            chamber=chamber,
        )
        new_ceo_admins.append(ceo_admin)

    User.objects.bulk_create(new_ceo_admins)
    Chamber.objects.bulk_update(
        chambers,
        fields=["ceo_email", "ceo_first_name", "ceo_last_name"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0013_storedmember_phone_alter_storedmember_state_and_more'),
        ('users', '0003_user_deleted_at_user_deleted_by_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='ceo_first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='CEO First Name'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='ceo_last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='CEO Last Name'),
        ),
        migrations.RunPython(
            populate_first_and_last_names_and_create_ceo_admin,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='chamber',
            name='ceo_name',
        ),
    ]
