# Generated by Django 4.2.7 on 2023-12-04 03:09

from django.db import migrations, models
import uuid


def populate_chamber_subdomain(apps, schema_editor) -> None:
    """Populate chamber subdomain with uuid."""
    Chamber = apps.get_model("chambers", "Chamber")
    chambers_with_no_subdomain = Chamber.objects.filter(
        subdomain__isnull=True,
    )
    for chamber in chambers_with_no_subdomain:
        chamber.subdomain = uuid.uuid4()
    Chamber.objects.bulk_update(
        chambers_with_no_subdomain,
        ("subdomain",),
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "chambers",
            "0014_remove_chamber_ceo_name_chamber_ceo_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storedmember",
            options={
                "verbose_name": "Stored Member",
                "verbose_name_plural": "Stored Members",
            },
        ),
        migrations.RunPython(
            populate_chamber_subdomain,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="chamber",
            name="subdomain",
            field=models.CharField(
                max_length=63,
                verbose_name="Subdomain",
            ),
            preserve_default=False,
        ),
    ]
