# Generated by Django 4.2.9 on 2024-01-15 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0016_chamber_external_id'),
        ('chambers', '0016_storedmembercontact'),
    ]

    operations = [
    ]
