# Generated by Django 4.2.7 on 2024-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0017_merge_20240115_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedmember',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Address 2'),
        ),
        migrations.AddField(
            model_name='storedmember',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID from old db'),
        ),
    ]
