# Generated by Django 4.2.10 on 2024-04-15 07:50

import django.core.validators
from django.db import migrations, models


def reduce_the_length_of_zip_code(apps, schema_editor):
    """Reduce the length of ZIP code to 10 characters."""
    StoredMember = apps.get_model("chambers", "StoredMember")
    stored_members = list(StoredMember.objects.all())
    for stored_member in stored_members:
        stored_member.zip = stored_member.zip[:10]
    StoredMember.objects.bulk_update(stored_members, ["zip"])


class Migration(migrations.Migration):
    dependencies = [
        ("chambers", "0019_storedmembercontact_external_id"),
    ]

    operations = [
        migrations.RunPython(reduce_the_length_of_zip_code),
        migrations.AlterField(
            model_name="storedmember",
            name="zip",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid ZIP code",
                        regex="^\\d{5}((-\\d{1,4})|(\\.0))?$",
                    ),
                ],
                verbose_name="Company Zip",
            ),
        ),
    ]
