# Generated by Django 4.2.2 on 2023-06-15 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('chambers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('status', models.CharField(choices=[('created', 'Campaign Created'), ('open', 'Open Renewal'), ('live', 'Go Live'), ('done', 'Mark As Done')], max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('timeline', models.CharField(max_length=20, verbose_name='Timeline Applied')),
                ('goal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Goal')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='chambers.chamber', verbose_name='Chamber ID')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Unit Cost')),
                ('benefits', models.TextField(blank=True, verbose_name='Benefits')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('conditions', models.TextField(blank=True, verbose_name='Conditions')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('pre_trc_income', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Pre TRC Income')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_included_in_renewal', models.BooleanField(default=True, verbose_name='Included In Renewal')),
                ('is_hidden_next_year', models.BooleanField(default=False, verbose_name='Hidden Next Year')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(blank=True, max_length=1000, upload_to='', verbose_name='Media File')),
                ('content_type', models.CharField(max_length=255, verbose_name='Content Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='campaigns.product', verbose_name='Product ID')),
            ],
            options={
                'verbose_name': 'Product Media',
                'verbose_name_plural': 'Product Medias',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(max_length=1000, upload_to='', verbose_name='Image')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='campaigns.campaign', verbose_name='Campaign ID')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='campaigns.productcategory', verbose_name='Product Category ID'),
        ),
        migrations.CreateModel(
            name='LevelInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cost')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='members.contract', verbose_name='Contract ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='campaigns.level', verbose_name='Level ID')),
            ],
            options={
                'verbose_name': 'Level Instance',
                'verbose_name_plural': 'Level Instances',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='campaigns.product', verbose_name='Product ID'),
        ),
    ]
