# Generated by Django 4.2.2 on 2023-07-06 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0003_campaign_deleted_at_campaign_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductMedia',
            new_name='ProductAttachment',
        ),
        migrations.AlterModelOptions(
            name='productattachment',
            options={'verbose_name': 'Product Attachment', 'verbose_name_plural': 'Product Attachments'},
        ),
    ]
