# Generated by Django 4.2.2 on 2023-07-17 03:16

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0006_team_goal_alter_usercampaign_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercampaign',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=254, verbose_name='Email address'),
        ),
    ]
