# Generated by Django 4.2.2 on 2023-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0007_alter_usercampaign_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercampaign',
            name='role',
            field=models.CharField(choices=[('chamber_chair', 'Chamber Chair'), ('vice_chair', 'Vice Chair'), ('team_captain', 'Team Captain'), ('volunteer', 'Volunteer')], default='volunteer', max_length=255, verbose_name='Role'),
        ),
    ]
