# Generated by Django 4.2.2 on 2023-07-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('campaigns', '0009_alter_campaign_name_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelinstance',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Declined At'),
        ),
    ]
