# Generated by Django 4.2.2 on 2023-08-14 10:16

import config.settings.common.paths
import django.contrib.postgres.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_productcategory_background_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercampaign',
            name='company',
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, max_length=512, null=True, upload_to=config.settings.common.paths._default_media_path, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company address'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='company_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company city'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='company_country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company country'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='company_fax_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company fax number'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company name'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company phone number'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='company_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Company state'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='company_zip_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company zip code'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='preferred_contact_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=[], size=None, verbose_name='Preferred contact methods'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
