# Generated by Django 4.2.2 on 2023-08-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_remove_usercampaign_company_usercampaign_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='has_trades',
            field=models.BooleanField(default=False, verbose_name='Has Trades'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_vice_chairs',
            field=models.BooleanField(default=False, verbose_name='Has Vice Chairs'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='report_close_on_end',
            field=models.CharField(max_length=20, null=True, verbose_name='Report Close On End'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='report_close_on_start',
            field=models.CharField(max_length=20, null=True, verbose_name='Report Close On Start'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='timeline',
            field=models.CharField(max_length=255, verbose_name='Timeline Applied'),
        ),
    ]
