# Generated by Django 4.2.2 on 2023-09-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_remove_usercampaign_company_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_renewed',
            field=models.BooleanField(default=False, verbose_name='Is Renewed'),
        ),
    ]
