# Generated by Django 4.2.2 on 2023-09-17 05:40

from django.db import migrations, models


def populate_campaign_status_field(apps, schema_editor) -> None:
    """Populate new renewal status field for all campaign data."""
    Campaign = apps.get_model("campaigns", "Campaign")
    Campaign.objects.filter(status="open").update(status="renewal")


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_campaign_is_renewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('created', 'Campaign Created'), ('renewal', 'Open Renewal'), ('live', 'Go Live'), ('done', 'Mark As Done')], default='created', max_length=20, verbose_name='Status'),
        ),
        migrations.RunPython(
            populate_campaign_status_field,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
