# Generated by Django 4.2.5 on 2023-09-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercampaign',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='usercampaign',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Last name'),
        ),
    ]
