# Generated by Django 4.2.5 on 2023-09-25 13:26

from django.db import migrations, models


def populate_product_category_order_data(apps, schema_editor) -> None:
    """Populate product category data with order field for each campaign."""
    ProductCategory = apps.get_model("campaigns", "ProductCategory")
    Campaign = apps.get_model("campaigns", "Campaign")
    categories = ProductCategory.objects.select_related("campaign")
    updated_categories = {
        category: idx
        for campaign in Campaign.objects.all()
        for idx, category in enumerate(categories.filter(campaign=campaign))
    }
    for category, idx in updated_categories.items():
        category.order = idx
    ProductCategory.objects.bulk_update(
        updated_categories.keys(),
        fields=["order"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_alter_usercampaign_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('order',), 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_product_category_order_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
