# Generated by Django 4.2.5 on 2023-10-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_alter_productcategory_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelinstance',
            name='trade_with',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Trade with'),
        ),
    ]
