# Generated by Django 4.2.5 on 2023-10-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0022_levelinstance_trade_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_hidden_next_year',
        ),
    ]
