# Generated by Django 4.2.5 on 2023-10-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0023_note'),
        ('campaigns', '0023_remove_product_is_hidden_next_year'),
    ]

    operations = [
    ]
