# Generated by Django 4.2.5 on 2023-10-11 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_contractsharedcreditinfo_and_more'),
        ('campaigns', '0024_merge_20231010_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelinstance',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='members.contract', verbose_name='Contract ID'),
        ),
    ]
