# Generated by Django 4.2.5 on 2023-10-18 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_alter_note_options_alter_note_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='managed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to='campaigns.usercampaign', verbose_name='Managed by'),
        ),
        migrations.AlterField(
            model_name='usercampaign',
            name='role',
            field=models.CharField(choices=[('chamber_chair', 'Chamber Chair'), ('vice_chair', 'Vice Chair'), ('team_captain', 'Team Captain'), ('volunteer', 'Volunteer'), ('chamber_admin', 'Chamber Admin')], default='volunteer', max_length=255, verbose_name='Role'),
        ),
    ]
