# Generated by Django 4.2.5 on 2023-10-23 03:50

from django.db import migrations, models
from django.db.models import functions


def populate_campaign_year(apps, schema_editor) -> None:
    """Populate correct year for campaigns from existing start date."""
    Campaign = apps.get_model("campaigns.Campaign")
    Campaign.objects.update(
        year=functions.ExtractYear(models.F("start_date")),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0028_team_managed_by_alter_usercampaign_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='year',
            field=models.IntegerField(default=2023, verbose_name='Year'),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_campaign_year,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Goal'),
        ),
    ]
