# Generated by Django 4.2.5 on 2023-10-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0014_remove_chamber_ceo_name_chamber_ceo_first_name_and_more'),
        ('campaigns', '0029_campaign_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercampaign',
            old_name='company_fax_number',
            new_name='company_mobile_number',
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_campaigns', to='chambers.storedmember', verbose_name='Stored Member'),
        ),
    ]
