# Generated by Django 4.2.5 on 2023-11-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0033_populate_campaign_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercampaign',
            name='sales_goal',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
