# Generated by Django 4.2.7 on 2023-11-20 00:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0036_auto_20231116_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Note text'),
        ),
    ]
