# Generated by Django 4.2.7 on 2023-11-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0036_auto_20231116_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='report_close_on_end',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Report Close On End'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='report_close_on_start',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Report Close On Start'),
            preserve_default=False,
        ),
    ]
