# Generated by Django 4.2.7 on 2023-12-07 07:03

from django.db import migrations, models


def populate_levels_amount_data(apps, schema_editor) -> None:
    """Populate level's amount with undeleted and undeclined instances."""
    Level = apps.get_model("campaigns", "Level")
    LevelInstance = apps.get_model("campaigns", "LevelInstance")
    levels = Level.objects.annotate(
        total_instance_count=models.Count(
            "instances",
            filter=models.Q(
                instances__deleted_at__isnull=True,
                instances__declined_at__isnull=True,
            ),
        ),
    )
    for level in levels:
        level.amount = level.total_instance_count
    Level.objects.bulk_update(levels, fields=["amount"])
    LevelInstance.objects.filter(contract__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0039_usercampaign_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=populate_levels_amount_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
