# Generated by Django 4.2.9 on 2024-01-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0041_campaign_external_id_campaign_external_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID in old DB'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='external_campaign_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Campaign ID in old DB'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='external_team_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Team ID in old DB'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='external_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID in old DB'),
        ),
    ]
