# Generated by Django 4.2.7 on 2024-01-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0037_alter_note_body'),
        ('campaigns', '0042_team_external_id_usercampaign_external_campaign_id_and_more'),
    ]

    operations = [
    ]
