# Generated by Django 4.2.9 on 2024-01-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0044_note_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID in old DB'),
        ),
        migrations.AddField(
            model_name='level',
            name='external_multiplier',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Multiplier in old DB'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID in old DB'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID in old DB'),
        ),
    ]
