# Generated by Django 4.2.9 on 2024-02-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0047_campaign_timeline_type_alter_campaign_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercampaign',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deactivated At'),
        ),
    ]
