# Generated by Django 4.2.9 on 2024-02-22 07:26
import datetime
import timezone_field.fields

from django.db import migrations, models


def populate_campaign_new_report_close_fields(apps, schema_editor):
    """Set values for `report_close_weekday` and `report_close_time`."""
    Campaign = apps.get_model("campaigns", "Campaign")
    Campaign.objects.update(
        report_close_weekday=models.Case(
            models.When(report_close_on_start=models.Value("Monday"), then=0),
            models.When(report_close_on_start=models.Value("Tuesday"), then=1),
            models.When(
                report_close_on_start=models.Value("Wednesday"),
                then=2,
            ),
            models.When(
                report_close_on_start=models.Value("Thursday"),
                then=3,
            ),
            models.When(report_close_on_start=models.Value("Friday"), then=4),
            models.When(
                report_close_on_start=models.Value("Saturday"),
                then=5,
            ),
            models.When(report_close_on_start=models.Value("Sunday"), then=6),
            default=models.Value(0),
        ),
        report_close_time=models.Value(datetime.time(1, 0, 0)),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0048_usercampaign_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='report_close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Report Close Time'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='report_close_weekday',
            field=models.IntegerField(blank=True, null=True, verbose_name='Report Close Weekday'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='US/Central', verbose_name='Timezone'),
        ),
        migrations.RunPython(
            populate_campaign_new_report_close_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='report_close_on_end',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='report_close_on_start',
        ),
    ]
