# Generated by Django 4.2.10 on 2024-04-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0051_alter_level_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productattachment",
            options={
                "ordering": ("order",),
                "verbose_name": "Product Attachment",
                "verbose_name_plural": "Product Attachments",
            },
        ),
        migrations.AddField(
            model_name="productattachment",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order",
            ),
            preserve_default=False,
        ),
    ]
