# Generated by Django 4.2.10 on 2024-03-19 08:54

from django.db import migrations, models


def populate_user_campaigns_phone(apps, schema_editor):
    """Populate `UserCampaign` new phone fields."""
    UserCampaign = apps.get_model("campaigns", "UserCampaign")
    user_campaigns = list(
        UserCampaign.objects.all().only(
            "id",
            "work_phone",
            "mobile_phone",
            "user",
        ).prefetch_related("user"),
    )
    for user_campaign in user_campaigns:
        user_campaign.work_phone = user_campaign.user.work_phone
        user_campaign.mobile_phone = user_campaign.user.mobile_phone
    UserCampaign.objects.bulk_update(
        user_campaigns,
        fields=("work_phone", "mobile_phone"),
        batch_size=5000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0053_populate_product_attachment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercampaign',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='usercampaign',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Work phone'),
        ),
        migrations.RunPython(
            populate_user_campaigns_phone,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
