# Generated by Django 4.2.2 on 2023-07-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('resources', '0002_resource_deleted_at_resource_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('image', 'Image')], default='pdf', max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='user_group',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('chamber_admin', 'Chamber Admin'), ('chamber_chair', 'Chamber Chair'), ('vice_chair', 'Vice Chair'), ('team_captain', 'Team Captain'), ('volunteer', 'Volunteer')], default='chamber_admin', max_length=255),
        ),
    ]
