# Generated by Django 4.2.2 on 2023-08-17 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0011_storedmember_address'),
        ('resources', '0003_resource_file_type_resource_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='chamber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='chambers.chamber', verbose_name='Chamber'),
        ),
    ]
