# Generated by Django 4.2.2 on 2023-08-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resourcecategory_chamber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('doc', 'Document'), ('pdf', 'PDF'), ('video', 'Video'), ('image', 'Image')], default='pdf', max_length=255),
        ),
    ]
