# Generated by Django 4.2.2 on 2023-09-14 08:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_resource_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='user_group',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('super_admin', 'Super Admin'), ('chamber_admin', 'Chamber Admin'), ('chamber_chair', 'Chamber Chair'), ('vice_chair', 'Vice Chair'), ('team_captain', 'Team Captain'), ('volunteer', 'Volunteer')], default='chamber_admin', max_length=255), default=['super_admin'], size=None),
            preserve_default=False,
        ),
    ]
