# Generated by Django 4.2.7 on 2023-11-22 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='resources.resourcecategory', verbose_name='Parent Category'),
        ),
    ]
