# Generated by Django 4.2.7 on 2024-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_provide_default_resourcecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID from old db'),
        ),
    ]
