# Generated by Django 4.2.9 on 2024-02-13 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('job_kwargs', models.JSONField(default=dict, help_text='Keyword parameters required for job initialization. Should look like {"chamber_ids": [546]}', verbose_name='Job kwargs')),
                ('traceback', models.TextField(blank=True, default=str, help_text='Python traceback in case of import error', verbose_name='Traceback')),
                ('error_message', models.CharField(blank=True, default=str, help_text='Python error message in case of import error', max_length=128, verbose_name='Error message')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Import confirmed'), ('IMPORTING', 'Importing'), ('IMPORTED', 'Imported'), ('IMPORT_ERROR', 'Import error')], default='CREATED', max_length=20, verbose_name='Job Status')),
                ('result', models.JSONField(default=dict, help_text='Number of imported objects per instance.', verbose_name='Job result')),
                ('task_id', models.CharField(default=str, help_text='Celery task ID that start importing', max_length=36, verbose_name='Task ID')),
                ('created_by', models.ForeignKey(editable=False, help_text='User which started job', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
            },
        ),
    ]
