# Generated by Django 4.2.9 on 2024-02-26 01:56

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0019_storedmembercontact_external_id'),
        ('historical_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldChamber',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('old_id', models.IntegerField(blank=True, help_text='Chamber from which current chamber is duplicated', null=True, verbose_name='Original Chamber Id')),
                ('originally_created', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Old Chamber',
                'verbose_name_plural': 'Old Chambers',
            },
        ),
        migrations.AddField(
            model_name='dataimportjob',
            name='target_chamber',
            field=models.ForeignKey(help_text='Chamber which data are imported into', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chambers.chamber', verbose_name='Target Chamber'),
        ),
    ]
