# Generated by Django 4.2.2 on 2023-06-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('chambers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chamber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chambers.chamber', verbose_name='Chamber'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('chamber_admin', 'Chamber Admin'), ('chamber_chair', 'Chamber Chair'), ('vice_chair', 'Vice Chair'), ('team_captain', 'Team Captain'), ('volunteer', 'Volunteer')], default='volunteer', max_length=255, verbose_name='Role'),
        ),
    ]
