# Generated by Django 4.2.2 on 2023-06-30 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('chambers', '0004_remove_chamber_trc_coord_name_and_more'),
        ('users', '0003_user_deleted_at_user_deleted_by_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chamber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chambers.chamber', verbose_name='Chamber'),
        ),
    ]
