# Generated by Django 4.2.2 on 2023-07-10 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_user_phone_alter_user_chamber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('favorite_candy', models.TextField(blank=True, verbose_name='Favorite candy')),
                ('favorite_drink', models.TextField(blank=True, verbose_name='Favorite drink')),
                ('favorite_restaurant', models.TextField(blank=True, verbose_name='Favorite restaurant')),
                ('favorite_movie', models.TextField(blank=True, verbose_name='Favorite movie')),
                ('hobbies', models.TextField(blank=True, verbose_name='Hobbies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
