# Generated by Django 4.2.2 on 2023-07-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='fax',
            field=models.CharField(blank=True, max_length=15, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Home phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Mobile phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Twitter URL'),
        ),
    ]
