# Generated by Django 4.2.2 on 2023-08-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_chamber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Home address'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Home city'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Home state'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_zip_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Home zip code'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Home phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mobile phone'),
        ),
    ]
