# Generated by Django 4.2.7 on 2023-11-30 02:53

import citext.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_birthday_user_home_address_user_home_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=citext.fields.CIEmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
