# Generated by Django 4.2.7 on 2023-11-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
    ]
