# Generated by Django 4.2.7 on 2023-12-07 02:47

import citext.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userpreference_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=citext.fields.CIEmailField(max_length=254, verbose_name='Email address'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('email',), name='unique_user_email'),
        ),
    ]
