# Generated by Django 4.2.9 on 2024-02-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Work phone'),
        ),
    ]
