# Generated by Django 4.2.2 on 2023-07-05 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chambers', '0004_remove_chamber_trc_coord_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('open', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='not_started', max_length=255, verbose_name='Status')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_timelines', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='chambers.chamber', verbose_name='Chamber')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_timelines', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
            },
        ),
        migrations.CreateModel(
            name='TimelineAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(blank=True, max_length=1000, upload_to='', verbose_name='Media File')),
                ('content_type', models.CharField(max_length=255, verbose_name='Content Type')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='timelines.timeline', verbose_name='Timeline')),
            ],
            options={
                'verbose_name': 'Timeline Attachment',
                'verbose_name_plural': 'Timeline Attachments',
            },
        ),
    ]
