# Generated by Django 4.2.2 on 2023-07-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='category',
            field=models.CharField(default=1, max_length=255, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
