# Generated by Django 4.2.2 on 2023-09-17 05:40

from django.db import migrations, models


def populate_timeline_status_field(apps, schema_editor) -> None:
    """Populate new in_progress status field for all timeline data."""
    Timeline = apps.get_model("timelines", "Timeline")
    Timeline.objects.filter(status="open").update(status="in_progress")


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_timelinecategory_alter_timeline_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed')], default='not_started', max_length=255, verbose_name='Status'),
        ),
        migrations.RunPython(
            populate_timeline_status_field,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
