# Generated by Django 4.2.5 on 2023-09-23 14:41

from django.db import migrations, models


def populate_timeline_order_data(apps, schema_editor) -> None:
    """Populate timeline data with order field for each chamber."""
    Timeline = apps.get_model("timelines", "Timeline")
    Chamber = apps.get_model("chambers", "Chamber")
    timelines = Timeline.objects.select_related("chamber")
    updated_timelines = {
        timeline: idx
        for chamber in Chamber.objects.all()
        for idx, timeline in enumerate(timelines.filter(chamber=chamber))
    }
    for timeline, idx in updated_timelines.items():
        timeline.order = idx
    Timeline.objects.bulk_update(updated_timelines.keys(), fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0004_alter_timeline_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ('order',), 'verbose_name': 'Timeline', 'verbose_name_plural': 'Timelines'},
        ),
        migrations.AddField(
            model_name='timeline',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_timeline_order_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
