# Generated by Django 4.2.5 on 2023-10-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0005_alter_timeline_options_timeline_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assigned To'),
        ),
    ]
