# Generated by Django 4.2.7 on 2023-11-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0007_migrate_timeline_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='assigned_to',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Assigned To'),
            preserve_default=False,
        ),
    ]
