# Generated by Django 4.2.9 on 2024-02-02 07:47

from django.db import migrations, models
import django_extensions.db.fields
from apps.timelines.constants import TimelineTypeChoice


def provide_default_timeline_types(apps, schema_editor):
    """Provide default timeline types in system."""
    TimelineType = apps.get_model("timelines", "TimelineType")
    TimelineType.objects.bulk_create(
        [
            TimelineType(name=TimelineTypeChoice.WITHOUT_VICE_CHAIR),
            TimelineType(name=TimelineTypeChoice.WITH_VICE_CHAIR),
        ],
        ignore_conflicts=True,
    )


def populate_current_timelines(apps, schema_editor):
    """Populate current timelines with `type_name` and `type` fields."""
    Timeline = apps.get_model("timelines", "Timeline")
    TimelineType = apps.get_model("timelines", "TimelineType")
    timelines = Timeline.objects.all()
    for timeline in timelines:
        timeline.type = TimelineType.objects.filter(
            name=timeline.type_name,
        ).first()
    Timeline.objects.bulk_update(timelines, ["type"])


def reverse_populate_current_timelines(apps, schema_editor):
    """Reverse current timelines with `type` and `type_name` fields."""
    Timeline = apps.get_model("timelines", "Timeline")
    timelines = Timeline.objects.all()
    for timeline in timelines:
        timeline.type_name = timeline.type.name if timeline.type else ""
    Timeline.objects.bulk_update(timelines, ["type_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0010_import_default_timelines'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted_at', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(choices=[('23os_tc', '23OS TC'), ('23os_vc', '23OS VC')], max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Timeline Type',
                'verbose_name_plural': 'Timeline Types',
            },
        ),
        migrations.RunPython(
            provide_default_timeline_types,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RenameField(
            model_name='timeline',
            old_name='type',
            new_name='type_name',
        ),
        migrations.AddField(
            model_name='timeline',
            name='type',
            field=models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='timelines', to='timelines.timelinetype', verbose_name='Type'),
        ),
        migrations.RunPython(
            populate_current_timelines,
            reverse_code=reverse_populate_current_timelines,
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='type_name',
        ),
    ]
