name: Run pre-commmit hooks

on:
  pull_request:
  push:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Fallback to plain text output for reducing docker output
  # https://github.com/docker/compose/issues/8753#issuecomment-934473781
  BUILDKIT_PROGRESS: plain

jobs:
  cr:
    runs-on: saritasa-rocks-eks
    timeout-minutes: 15
    env:
      DJANGO_SETTINGS_MODULE: config.settings.local
    steps:
      - uses: actions/checkout@v4
      - name: Cache local dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/local_build.txt') }}
      - name: Cache development dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/development.txt') }}
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup dendencies to build MySQL client
        run: sudo apt-get update && sudo apt-get install -y python3-dev build-essential python3-pkgconfig default-libmysqlclient-dev
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SARITASA_LLC_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SARITASA_LLC_DOCKERHUB_TOKEN }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install --requirement requirements/local_build.txt
      - name: Prepare env
        run: |
          inv ci.prepare
      - name: Run checks
        run: |
          inv git.run-hooks
